In [130]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.ticker as plticker
from sklearn.model_selection import train_test_split
from sklearn import linear_model,datasets
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [131]:
diabetes = pd.read_csv('diabetes.csv')

In [104]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [106]:
# Use only one feature
diabetes_X = diabetes['Glucose']
diabetes_y = diabetes['Outcome']


In [107]:
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]
diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]

In [108]:
diabetes_X_train.head()

0    148
1     85
2    183
3     89
4    137
Name: Glucose, dtype: int64

In [109]:
diabetes_X_test.head()

748    187
749    162
750    136
751    121
752    108
Name: Glucose, dtype: int64

In [110]:
diabetes_y_train.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [111]:
diabetes_y_test.head()

748    1
749    1
750    1
751    0
752    0
Name: Outcome, dtype: int64

In [134]:
lm = linear_model.LinearRegression()

In [126]:
x_train,x_test,y_train,y_test=train_test_split(diabetes_X,diabetes_y,test_size=0.2,random_state=4)

In [135]:
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [119]:
y_test

390    0
146    0
136    0
420    0
328    1
72     1
110    1
254    1
215    1
559    0
67     0
112    0
66     1
74     0
65     0
179    1
236    1
661    1
33     0
273    0
637    0
295    0
462    0
155    1
276    1
428    0
113    0
261    1
164    1
17     1
      ..
481    0
380    0
582    0
737    0
624    0
378    1
397    1
430    0
70     1
249    0
283    1
224    0
665    0
253    0
31     1
228    0
615    0
629    0
563    0
698    0
317    1
708    1
753    1
628    0
307    0
374    0
288    0
282    0
754    1
363    1
Name: Outcome, Length: 154, dtype: int64

In [113]:
lm.fit([x_train],[y_train])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [114]:
lm.intercept_

array([0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
       1., 1., 1., 0., 0.

In [115]:
print('the coefficents:\n',lm.coef_)

the coefficents:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [133]:
#y_test

z = lm.predict([y_test])
#print("Mean sqaured error: %.2f" %np.mean((lm.predict(x_test)- x_test)**2))

ValueError: shapes (1,154) and (614,614) not aligned: 154 (dim 1) != 614 (dim 0)

In [76]:
print('variance score is:  %.2f'%lm.score([diabetes_X_test],[diabetes_y_test]))

ValueError: shapes (1,20) and (748,748) not aligned: 20 (dim 1) != 748 (dim 0)